### ISSUE TITLE
All methods cannot be used

### ISSUE THREAD

**Issue by tangtang520** [tcort/wkhtmltox#2]
All methods cannot be used

**Comment by tcort** [comment]
There isn't enough information in your issue report for me to diagnose the issue you're having. Can you answer these questions for me:

* what methods are you wanting to use?
* why can't you use them? (are they not available? is there an error?)
* what version of wkhtmltopdf are you using?
* what version of node are you using?
* what platform are you on? (Linux, Mac OS X, etc)

**Comment by tcort** [comment]
I have not received a response in over a year, so I'm going to assume that this is no longer an issue for you. If it is still a problem, please re-open and provide more detail.
