### ISSUE TITLE
Cross Platform Support

### ISSUE THREAD

**Issue by stramel** [tcort/wkhtmltox#3]
Would love to see this setup for cross platform support. Doesn't seem to hard to achieve. May give it a shot if I can find time.

**Comment by tcort** [comment]
Can you be a little more specific about what your target platform(s) are, what you're trying, and what isn't working?

It's working fine for me on FreeBSD, Mac OS X, and Linux.

**Comment by stramel** [comment]
@tcort Sorry for the vague description. I run Linux at home and this worked great for me, however at work I am forced to run WIndows 7. It can't find `/bin/sh` on Windows 7.

**Comment by tcort** [comment]
I've published version `1.0.10` which doesn't have `modern-syslog` in it's dependency chain which was causing an installation problem. I don't have access to a Windows machine, so I can't test if it works on Windows, but at least that installation road block is removed.
